# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to=b'')),
                ('product_description', models.TextField()),
                ('product_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
