# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160317_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_rate',
            field=models.IntegerField(default=0),
        ),
    ]
