# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brend',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_orm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='notebook', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=None, upload_to=b''),
        ),
    ]
