# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_auto_20160326_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
