# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_product_users_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_products', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'basket',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='product',
            name='users_liked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
