# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20160524_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='chosen_products',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
