# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20160524_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_screen_resolution',
            field=models.FloatField(default=0),
        ),
    ]
