# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_product_screen_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_products', models.CharField(max_length=200)),
                ('orders_cost', models.IntegerField(default=0)),
                ('adress_of_orderer', models.CharField(max_length=200)),
                ('orders_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
