# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orders_phone_number',
            field=models.CharField(default=3254362364, max_length=100),
        ),
    ]
