# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20160530_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_filtered_products', models.CharField(default='[]', max_length=1000)),
            ],
            options={
                'db_table': 'filtered_products',
            },
        ),
    ]
