# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_filteredproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteredproducts',
            name='ip_of_user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
