# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_filteredproducts_ip_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='chosen_products',
            field=models.CharField(default='{}', max_length=200),
        ),
    ]
