# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20160615_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_pay_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
