# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_orders_order_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name_of_user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
