# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20160616_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketOneClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_products', models.CharField(default='{}', max_length=200)),
            ],
            options={
                'db_table': 'basket_one_click',
            },
        ),
    ]
