# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_basketoneclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_exist',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
