# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@gmail.com', max_length=254)),
                ('emails_username', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user_email',
            },
        ),
    ]
