# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20160530_1127'),
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('products_watched', models.ManyToManyField(to='product.Product')),
            ],
            options={
                'db_table': 'ip_adress',
            },
        ),
        migrations.CreateModel(
            name='Product_watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=200)),
                ('list_of_watched_products', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'watched_product',
            },
        ),
    ]
