# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20160530_1127'),
        ('loginsys', '0002_ip_adress_product_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_watched',
            name='list_of_watched_products',
        ),
        migrations.AddField(
            model_name='product_watched',
            name='list_of_watched_products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
