# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_auto_20160606_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip_adress',
            old_name='products_watched',
            new_name='list_of_products',
        ),
    ]
