# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0004_auto_20160606_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_adress',
            name='list_of_products',
        ),
        migrations.AddField(
            model_name='ip_adress',
            name='list_of_products',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.RemoveField(
            model_name='product_watched',
            name='list_of_watched_products',
        ),
        migrations.AddField(
            model_name='product_watched',
            name='list_of_watched_products',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
