# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0005_auto_20160607_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_email',
            name='adress_of_user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
