# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0006_user_email_adress_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_email',
            name='telephone_of_user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
